# -*- coding: utf-8 -*-
"""CS301-Midterm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPjPFY_wRBpWrFM5vrQA3b6zIgk_asCI

# Dataset Description

**Name:** Student Exam Scores

**Source:** https://www.kaggle.com/datasets/saadaliyaseen/analyzing-student-academic-trends?resource=download

**Size:** 200

**Context:** The students dataset includes details of 200 students, covering study hours, sleep duration, attendance, past scores, and final exam results.

**Research questions:**



1.   How does sleep duration affect final exam results?
2.   Which factors are the strongest predictor of final exam results?

----

***NOTE:*** We've created a GitHub repo for our Midterm project, hosted [here](https://github.com/avr33-boop/CS301-Midterm-Project/). It contains everything used in the project, *including the dataset*. This Notebook will obtain the dataset from GitHub if it's not already uploaded.

#Data Cleaning & Preparation

The dataset was checked and there was no sign of inconsistent data, duplicate entries, or missing values.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

file_path = '/content/student_exam_scores.csv'
gh_url = 'https://github.com/avr33-boop/CS301-Midterm-Project/'

try:
  df = pd.read_csv(file_path)
except:
  df = pd.read_csv(gh_url + 'blob/main/content/student_exam_scores.csv?raw=true')

print('Sum of Duplicated Entries: ', df.duplicated().sum())
print('\n')

print('Sum of Missing value entries')
print(df.isnull().sum())
print('\n')

print('Type for each row')
print(df.dtypes)

"""#Exploratory Data Analysis

The correlation between Exam Score and Sleep Hours is 0.18, which is relatively low. This suggests a weak relationship between the two variables, indicating that Exam Score is not strongly influenced by Sleep Hours. Running the correlation between Exam Scores and Attendance Percent shows that there isn't much of a relation there either.

However, the correlation between a student's Exam Score and how many hours they studied is rather high, at ~0.78. This means that there is a strong relationship between how well a student does, and how many hours they studied.
"""

print("Descriptive Statistics: \n")
print(df.describe())

print('\nCorrelation between Exam Score and Sleep Hours: \n')
print(df[['sleep_hours', 'exam_score']].corr())

print('\nCorrelation between Exam Score and Hours Studied: \n')
print(df[['hours_studied', 'exam_score']].corr())

print('\nCorrelation between Exam Score and Attendance Percent: \n')
print(df[['attendance_percent', 'exam_score']].corr())

print('\nCorrelation between Exam Score and Previous Exam Score: \n')
print(df[['previous_scores', 'exam_score']].corr())

"""#Data Visualization

Below are histograms of students' Final Exam scores, and Previous Exam scores, as well as a box and whisker plot to accompany them. It shows:

- the disparity between students' initial, midterm grade, and their final grades
- and the distribution between their grades for each exam
  - In their first, midterm exam, *most students scored higher on the scale*, albeit with a wider standard deviation. This relatively good turnout may have led to *overconfidence* on the student's part
  - Then, in their final exam, *none of the students did well*, and there was an overall smaller standard deviation among scores. This directly reflects that the entire class failed D:
"""

import seaborn as sns

f, ax = plt.subplots(2,2, sharex=True, figsize=(12, 5), gridspec_kw={"height_ratios": (.15, .85)})

sns.boxplot(x=df['exam_score'], ax=ax[0,0])
sns.histplot(x=df['exam_score'], bins=12, kde=True, stat='density', ax=ax[1,0])

ax[0,0].set(yticks=[])
sns.despine(ax=ax[1,0])
sns.despine(ax=ax[0,0], left=True)

sns.boxplot(x=df['previous_scores'], ax=ax[0,1])
sns.histplot(x=df['previous_scores'], bins=12, kde=True, stat='density', ax=ax[1,1])

ax[0,1].set(yticks=[])
sns.despine(ax=ax[1,1])
sns.despine(ax=ax[0,1], left=True)

"""Below is a plot of the student's exam scores vs their Sleep Hours, Hours Studied, Attendance Percent, and their Previous Exam Scores. On top of these plots are *lines of best fit*; that is to say, if a relation exists, that line will best capture said relation.

- As we said before, there isn't much of a correlation between a student's exam score, and their attendance percent or hours of sleep. The plots below illustrate that well; the lines of best fit *do* go through the data well, but the *variance* is way too high.
- On the other hand, a student's hours studied has a *very strong* correlation with how they performed on their final exam. This is evident as the line of best fit not only fits the data well, but the *variance is minimal*.
- Finally, the fourth graph shows that even though there is a mild correlation (0.43) between a student's previous exam score and their final exam score, there isn't much. This is to be expected though, as a standard class usually has a mix of high-scorers, low-scorers, and those who do bad on their first exam, and improve by their second.
"""

fig, ax = plt.subplots(2,2, figsize=(12,8))

slope1, intercept1 = np.polyfit(df['sleep_hours'], df['exam_score'], 1)
line1 = slope1 * df['sleep_hours'] + intercept1
ax[0,0].plot(df['sleep_hours'], line1, color='red', label='Line of Best Fit')
ax[0,0].scatter(df['sleep_hours'], df['exam_score'], label='Data Points')
ax[0,0].set_xlabel('Sleep Hours')
ax[0,0].set_ylabel('Exam Score')
ax[0,0].set_title('Relationship between Sleep Hours and Exam Scores')

slope2, intercept2 = np.polyfit(df['hours_studied'], df['exam_score'], 1)
line2 = slope2 * df['hours_studied'] + intercept2
ax[0,1].plot(df['hours_studied'], line2, color='red', label='Line of Best Fit')
ax[0,1].scatter(df['hours_studied'], df['exam_score'])
ax[0,1].set_xlabel('Hours Studied')
ax[0,1].set_ylabel('Exam Score')
ax[0,1].set_title('Relationship between Hours Studied and Exam Scores')

slope3, intercept3 = np.polyfit(df['attendance_percent'], df['exam_score'], 1)
line3 = slope3 * df['attendance_percent'] + intercept3
ax[1,0].plot(df['attendance_percent'], line3, color='red', label='Line of Best Fit')
ax[1,0].scatter(df['attendance_percent'], df['exam_score'])
ax[1,0].set_xlabel('Attendance Percent')
ax[1,0].set_ylabel('Exam Score')
ax[1,0].set_title('Relationship between Attendance Percent and Exam Scores')

slope4, intercept4 = np.polyfit(df['previous_scores'], df['exam_score'], 1)
line4 = slope4 * df['previous_scores'] + intercept4
ax[1,1].plot(df['previous_scores'], line4, color='red', label='Line of Best Fit')
ax[1,1].scatter(df['previous_scores'], df['exam_score'])
ax[1,1].set_xlabel('Previous Exam Scores')
ax[1,1].set_ylabel('Exam Score')
ax[1,1].set_title('Relationship between Previous Exam Scores and Final Exam Scores')

fig.tight_layout()
plt.show()

"""#Findings & Insights

In conclusion, we found that our initial assumption, that sleep duration affects a student's final score, is largely incorrect. When we calculated the correlation between a student's final score and sleep duration (using `df.corr()`), we found that this correlation is *only 0.188*. And since strong correlations are closer to 1, these two variables are obviously not related. The scatterplots and lines of best fit depict this even further, visually.

We then went on to test other variables similarly, and found that a student's *number of hours studied* has the *HIGHEST correlation* with their final exam scores. This is evident, not only because the correlation value is 0.78, but because the line of best fit *visually* fits the scatterplot data very well.

In addition to all this, we also found that there isn't much of a correlation between a student's previous exam score and their final exam score. This is to be expected though, since a standard class usually has a mix of high-scorers, low-scorers, and those who do bad on their first exam, and improve by their second.

To summarize:

- Students who get a good nights sleep don't necessarily do well on their exams
- Students who attend class often *also* don't necessarily do well on their exams
- Students who did well on their first exam don't necessarily do well on their final, and likewise those who did bad don't necessarily do bad again
- And finally, students who *study BENEFIT THE MOST!!!*
"""